### ISSUE TITLE
python scripts.py build_db 报错 请问python版本是多少

### ISSUE THREAD

**Issue by jiangli373** [NetEaseGame/git-webhook#3]
按照readme上的方法安装：

执行下面的命令

`python scripts.py build_db` 

```
Traceback (most recent call last):
  File "scripts.py", line 8, in <module>
    from app.utils import StringUtil
  File "/srv/www/git-webhook/app/__init__.py", line 23, in <module>
    from celery import Celery, platforms
  File "/usr/local/lib/python2.7/dist-packages/celery/__init__.py", line 133, in <module>
    from celery import five  # noqa
  File "/usr/local/lib/python2.7/dist-packages/celery/five.py", line 153, in <module>
    from kombu.utils.compat import OrderedDict  # noqa
ImportError: cannot import name OrderedDict
```
报上面的错，OrderedDict已经安装过了

服务器是14.04

**Comment by hustcc** [comment]
我的运行和开发环境 Python 2.7。

**Comment by jiangli373** [comment]
`python --version`

`Python 2.7.6` 

我的也是2.7，奇怪了，上面那个报错一直过不去

**Comment by hustcc** [comment]
从 trace 报错来看，感觉好像是celery 版本的问题。

**Comment by jiangli373** [comment]
换了一台机器，安装成功了 谢谢啦
