### ISSUE TITLE
pip 安装之后运行失败

### ISSUE THREAD

**Issue by hustcc** [NetEaseGame/git-webhook#35]
具体出错信息为：

```shell
root@xxxx-xx-xx:/home/xxxxxx# gitwebhook config
Traceback (most recent call last):
  File "/usr/local/bin/gitwebhook", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: schema==0.6.5
```

**Comment by guyskk** [comment]
我在新创建的虚拟环境安装，一切正常。。
```
(py27) [guyskk@localhost lenc]$ gitwebhook config
OK: init configuration file into `/home/guyskk/.git-webhook/git_webhook_config.py`.
```

**Comment by hustcc** [comment]
我在两台内网机器试了，一台是可以的，但是另外一台是报上面的 trace 错误。
