### ISSUE TITLE
大大能帮帮忙吗，我ubuntu 的显示2.7为什么运行的时候是3.4

### ISSUE THREAD

**Issue by martin-huang** [NetEaseGame/git-webhook#47]
Traceback (most recent call last):
  File "/usr/local/bin/gitwebhook", line 7, in <module>
    from manage import run
  File "/usr/local/lib/python3.4/dist-packages/manage.py", line 161
    print __version__
                    ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by Zhai2333** [comment]
python2 *.py
